### ISSUE TITLE
why pincode is string?

### ISSUE THREAD

**Issue by 9868rishi** [suraj-996/lying-powder-9405#25]
https://github.com/suraj-996/lying-powder-9405/blob/3082b1ac778459a80a16678f221118581491b9df/Covid-19-VaccineScheduler/src/main/java/com/vs/model/VaccinationCenter.java#L24

**Comment by TruptiRG** [comment]
As Pincode is a part of the address, and addresses are meant to be fixed, here there is no need to perform any arithmetic operations on that so no point in taking it as an Integer, so it is taken as a string so that it can get used as it is means in the given format.
Also, if we consider in India the pin codes are of fixed length which is 6 digits, so by giving the proper validation we can use it.
